name: Update blog

on: [push, repository_dispatch]

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set Node.js
              uses: actions/setup-node@master
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: yarn install --pure-lockfile

            - name: Lint
              run: yarn run lint

            - name: Build
              run: yarn run build
              env:
                  GATSBY_ENV: 'prod'
            - name: Upload
              uses: sebastianpopp/ftp-action@releases/v2
              with:
                  host: anderwijs.nl
                  user: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  localDir: 'public'
                  #   options: '--delete'
