name: Validate

on: [push]

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Node.js
              uses: actions/setup-node@v3.8.2
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn install --pure-lockfile

            - name: Lint
              run: yarn run lint