name: Update blog

on: [push, repository_dispatch, workflow_dispatch]

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set Node.js
              uses: actions/setup-node@master
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: yarn install --pure-lockfile

            - name: Lint
              run: yarn run lint

            - name: Create .env file
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
                  envkey_GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
                  envkey_SITE_URL: ${{ secrets.SITE_URL }}
                  envkey_AAS_URL: ${{ secrets.AAS_URL }}
                  envkey_RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY }}
                  file_name: .env.production

            - name: Build
              run: yarn run build
              env:
                  GATSBY_ENV: 'prod'
            - name: Upload
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: anderwijs.nl
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: './public/'
                  exclude: |
                      **/aas2/**
                      **/start/**
                      **/wp/**
                      **/wiki/**
                      **/aardbei/**
                      **/cgi-bin/**
